[package]
name = "os1000lines_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[bin]]
name = "os1000lines_rust"
path = "src/kernel.rs"
