[tasks.BUILD]
description = "build"
script = ['''
#!/bin/bash
set -xue

QEMU=qemu-system-riscv32

cargo build --release

$QEMU -machine virt -bios default -nographic -serial mon:stdio --no-reboot \
  -d guest_errors \
  -kernel ./target/riscv32i-unknown-none-elf/release/os1000lines_rust
''']

[tasks.OBJDUMP]
description = "objdump using llvm-objdump"
script = ['''
llvm-objdump -d ./target/riscv32i-unknown-none-elf/release/os1000lines_rust
''']
